/*
  STM32 bare-metal example (STM32CubeIDE / a plain HAL project, no RTOS,
  superloop firmware). main.cpp is the usual entry point CubeIDE generates
  once you enable "C++" as the project language - eccles_rtmem.c compiles
  as a separate C translation unit and this file calls it through the
  extern "C" wrapper in eccles_rtmem.h, no glue code needed.

  Detected automatically here, no configuration needed:
    - budget: depends on which STM32 line you're on - 1 KB on the
      Cortex-M0/M0+ entry lines (F0/G0/L0/C0), 20 KB on everything bigger
      (F1/F3/F4/F7/L4/G4/H7/...). Override ECCLES_RT_MEM_SIZE if your
      part's actual RAM doesn't match either guess well.
    - locking: no RTOS is running, so this falls through to the generic
      Cortex-M PRIMASK save/disable/restore case - correct and safe for a
      single-core, single-threaded superloop, which is what this project
      structure is.
*/
extern "C" {
#include "eccles_rtmem.h"
#include "stm32f4xx_hal.h" /* swap for your line's HAL header */
}

static void SystemClock_Config(void);

int main(void) {
    HAL_Init();
    SystemClock_Config();

    eccles_rtmem_init();

    while (1) {
        uint8_t *frame = eccles_rt_malloc(64); /* e.g. a UART/CAN frame buffer */
        if (frame) {
            frame[0] = 0x01;
            /* ... build and send the frame ... */
            eccles_rt_free(frame);
        }
        HAL_Delay(10);
    }
}

static void SystemClock_Config(void) {
    /* ... generated by CubeMX for your specific board/clock tree ... */
}
